package util.Enums;

public enum AtributosTelaDeDetalhe {
    ESCOLARIDADE_INSITUICAO,
    ESCOLARIDADE_CURSO,
    ESCOLARIDADE_DATA_INICIO,
    ESCOLARIDADE_DATA_FIM,

    EXPERIENCIA_INSITUICAO,
    EXPERIENCIA_CARGO,
    EXPERIENCIA_DATA_INICIO,
    EXPERIENCIA_DATA_FIM

}
